import { Code2, Zap, ShieldCheck, Download, Copy } from "lucide-react";

export default function Optimization({ result }) {
  const copyCode = () => {
    if (result?.success) {
      navigator.clipboard.writeText(result.optimized_code);
      alert("Optimized code copied!");
    }
  };

  const downloadCode = () => {
    if (result?.success) {
      const blob = new Blob([result.optimized_code], { type: "text/plain" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = "optimized_code.py";
      a.click();
      URL.revokeObjectURL(url);
    }
  };

  return (
    <div className="optimization-page">
      <div className="optimization-header-card">
        <div>
          <h2>Optimization Engine</h2>
          <p>LLM-generated optimized implementation with runtime validation.</p>
        </div>

        <div className="optimization-badge">
          <Zap size={18} />
          Ready
        </div>
      </div>

      {result?.success ? (
        <>
          <div className="optimization-summary">
            <div className="optimization-stat purple-stat">
              <Zap size={34} />
              <h3>Optimization Status</h3>
              <p>{result.comparison?.accepted ? "Accepted" : "Not Accepted"}</p>
            </div>

            <div className="optimization-stat gold-stat">
              <ShieldCheck size={34} />
              <h3>Execution Validation</h3>
              <p>{result.after?.success ? "Passed" : "Failed"}</p>
            </div>

            <div className="optimization-stat green-stat">
              <Code2 size={34} />
              <h3>Generated Output</h3>
              <p>Executable Python Code</p>
            </div>
          </div>

          <div className="optimized-code-panel">
            <div className="optimized-code-header">
              <div>
                <h3>Optimized Code</h3>
                <p>Final code generated by the optimization engine.</p>
              </div>

              <div className="optimized-actions">
                <button onClick={copyCode}>
                  <Copy size={17} />
                  Copy
                </button>

                <button onClick={downloadCode}>
                  <Download size={17} />
                  Download
                </button>
              </div>
            </div>

            <pre>{result.optimized_code}</pre>
          </div>
        </>
      ) : (
        <div className="optimization-empty">
          Run analysis from Dashboard to generate optimized code.
        </div>
      )}
    </div>
  );
}